/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mobi_designmyapp_arpigl_engine_Engine */

#ifndef _Included_mobi_designmyapp_arpigl_engine_Engine
#define _Included_mobi_designmyapp_arpigl_engine_Engine
#ifdef __cplusplus
extern "C" {
#endif
#undef mobi_designmyapp_arpigl_engine_Engine_DEFAULT_CAMERA_ALTITUDE
#define mobi_designmyapp_arpigl_engine_Engine_DEFAULT_CAMERA_ALTITUDE 5.0
/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    newEngine
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_newEngine
  (JNIEnv *, jobject, jstring);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    freeEngine
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_freeEngine
  (JNIEnv *, jobject, jlong);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    init
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_init
  (JNIEnv *, jobject, jlong);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    refresh
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_refresh
  (JNIEnv *, jobject, jlong);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    unload
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_unload
  (JNIEnv *, jobject, jlong);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    wipe
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_wipe
  (JNIEnv *, jobject, jlong);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    step
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_step
  (JNIEnv *, jobject, jlong);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    addPoi
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;FFFDDD)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_addPoi
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jfloat, jfloat, jfloat, jdouble, jdouble, jdouble);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    removePoi
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_removePoi
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    setPoiPosition
 * Signature: (JLjava/lang/String;DDD)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_setPoiPosition
  (JNIEnv *, jobject, jlong, jstring, jdouble, jdouble, jdouble);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    setPoiColor
 * Signature: (JLjava/lang/String;FFF)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_setPoiColor
  (JNIEnv *, jobject, jlong, jstring, jfloat, jfloat, jfloat);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    isInit
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_isInit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    isAbleToDraw
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_isAbleToDraw
  (JNIEnv *, jobject, jlong);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    hasPoi
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_hasPoi
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    setSkyBox
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_setSkyBox
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    setSkyBoxEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_setSkyBoxEnabled
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    setSurfaceSize
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_setSurfaceSize
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    setEngineListener
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_setEngineListener
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    setCameraRotation
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_setCameraRotation
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    setCameraPosition2d
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_setCameraPosition2d
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    setCameraPosition
 * Signature: (JDDDZ)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_setCameraPosition
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble, jboolean);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    zoom
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_zoom
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    setOrigin
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_setOrigin
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    notifyTileAvailable
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_notifyTileAvailable
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    setTileNamespace
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_setTileNamespace
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    updateTileDiffuseMaps
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_updateTileDiffuseMaps
  (JNIEnv *, jobject, jlong);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine
 * Method:    selectPoi
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_selectPoi
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
