/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mobi_designmyapp_arpigl_engine_Engine_NativeFallthroughEngineListener */

#ifndef _Included_mobi_designmyapp_arpigl_engine_Engine_NativeFallthroughEngineListener
#define _Included_mobi_designmyapp_arpigl_engine_Engine_NativeFallthroughEngineListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine_NativeFallthroughEngineListener
 * Method:    newEngineListener
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_00024NativeFallthroughEngineListener_newEngineListener
  (JNIEnv *, jobject);

/*
 * Class:     mobi_designmyapp_arpigl_engine_Engine_NativeFallthroughEngineListener
 * Method:    freeEngineListener
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mobi_designmyapp_arpigl_engine_Engine_00024NativeFallthroughEngineListener_freeEngineListener
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
